name: Automatically Deployment

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest

    name: Deploying to surge

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setting .env
        run: |
          echo "TMDB_API_KEY=$TMDB_API_KEY" >> .env
          echo "TMDB_ACCESS_TOKEN=$TMDB_ACCESS_TOKEN" >> .env
          cat .env
          
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}

